### ISSUE TITLE
Does this work with multiple worksheets?

### ISSUE THREAD

**Issue by rymohr** [franciscop/drive-db#4]
Didn't see any mention of it in the readme.

**Comment by franciscop** [comment]
It's made to work with one worksheet by default, but nothing stops you from handling two with two caveats:

- You should define two different files for the cache.
- Keep two different instances

Note that there's also [a documentation file](https://github.com/franciscop/drive-db/blob/master/documentation.md) for some extra details. Example of the above (untested):

```js
var saleDrive = require('drive-db')({ sheet: SHEET_ID1, db: 'sales.json' });
var customerDrive = require('drive-db')({ sheet: SHEET_ID2, db: 'customers.json' });

// Load the file Customer Drive
customerDrive.load(customerLoaded);

// When Customer Drive has loaded
function customerLoaded(err, customerDB){

  // Load also the file Sale Drive
  saleDrive.load(saleLoaded);

  // When both of the previous spreadsheets are loaded
  function saleLoaded (err, ops){

    // Populate operations with customers
    var operations = ops.find().map(populate);

    // Data is ready to be used
    console.log(operations);
  });

  // Add a customer to each sale
  function populate (sale){
    sale.customer = customerDB.find({ id: sale.customer_id })[0];
    return sale;
  }
}
```

Then

**Comment by franciscop** [comment]
Maybe this could be a feature request to accept several spreadsheets and to make them work like this (same result as previous):

```js
var sheet = { sale: SHEET1, customer: SHEET2 };
var drive = require('drive-db')({ sheet: sheet });

drive.load(function(err, db){
  // The `customer_id` of `sale` is the same as the `id` of `customer`
  var operations = db.find('sale', {}).populate('customer', { id: 'customer_id' });
  console.log(operations);
});
```

While this is nice, it's not implemented and won't be in the foreseeable future due to lack of time and non-inmediate need for it. However if you feel like it, pull requests are welcome (:

**Comment by franciscop** [comment]
For future reference, this is using the old syntax where `load()` accepted a callback. Now `load()` will return a promise, to make sure to do `drive.load().then(callback)` or `const db = await drive.load();`
